apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\Kuba\.kompose\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: credit
  name: credit
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: credit
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\Kuba\.kompose\kompose.exe convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: credit
    spec:
      containers:
      - env:
        - name: SPRING_DATASOURCE_PASSWORD
          value: haslo
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysqldb:3306/mydb
        - name: SPRING_DATASOURCE_USERNAME
          value: user
        image: credit
        imagePullPolicy: ""
        name: credit
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
