apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\Kuba\.kompose\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: customer
  name: customer
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    io.kompose.service: customer
status:
  loadBalancer: {}
