apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\Kuba\.kompose\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: product
  name: product
spec:
  ports:
  - name: "8082"
    port: 8082
    targetPort: 8082
  selector:
    io.kompose.service: product
status:
  loadBalancer: {}
